{{- if .Values.createAdminSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchdb.fullname" . }}
  labels:
    app: {{ template "couchdb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  adminUsername: {{ template "couchdb.defaultsecret" .Values.adminUsername }}
  adminPassword: {{ template "couchdb.defaultsecret" .Values.adminPassword }}
  erlangCookie: {{ template "couchdb.defaultsecret" .Values.erlangFlags.setcookie }}
  cookieAuthSecret: {{ template "couchdb.defaultsecret" .Values.cookieAuthSecret }}
  inifile: {{ tpl (.Files.Get "ini/config.ini") . | b64enc }}
  seedlistinifile: {{ tpl (.Files.Get "ini/seedlist.ini") . | b64enc }}
{{- if .Values.prometheusPort.enabled }}
  prometheusinifile: {{ tpl (.Files.Get "ini/prometheus.ini") . | b64enc }}
{{- end }}
{{- if  .Values.adminHash  }}
  password.ini: {{ tpl (.Files.Get "ini/password.ini") . | b64enc }}
{{- end -}}
{{- end -}}
